package edu.iu.jrsalata;

import java.util.Queue;

/**
 * VisitorInterface defines a common interface for various types of visitors
 * that can process different kinds of statements in an assembler.
 */
public interface VisitorInterface {

    /**
     * Visits the given statement.
     *
     * @param statement the statement to be visited
     */
    public void visit(Statement statement);
    /**
     * Visits the given statement.
     *
     * @param statement the statement to be visited
     */
    public void visit(BaseStatement statement);
    /**
     * Visits the given statement.
     *
     * @param statement the statement to be visited
     */
    public void visit(SicStatement statement);
    /**
     * Visits the given statement.
     *
     * @param statement the statement to be visited
     */
    public void visit(SingleStatement statement);
    /**
     * Visits the given statement.
     *
     * @param statement the statement to be visited
     */
    public void visit(ExtendedStatement statement);
    /**
     * Visits the given statement.
     *
     * @param statement the statement to be visited
     */
    public void visit(DirectiveStatement statement);
    /**
     * Visits the given statement.
     *
     * @param statement the statement to be visited
     */
    public void visit(RegisterStatement statement);

    /**
     * Returns a queue of strings generated by this visitor
     */
    public Queue<String> getStrings();
}