COPY	START	0	.COPY FILE FROM INPUT TO OUTPUT
FIRST	STL	RETADR	.SAVE TETURN ADDRESS
	LDB	#LENGTH	.ESTABLISH BASE REGISTER
	BASE	LENGTH	
CLOOP	+JSUB	01036	.READ INPUT RECORD
	LDA	LENGTH	.TEST FOR EOF
	COMP	#0	
	JEQ	ENDFIL	.EXIT IF EOF FOUND
	+JSUB	0105d	.WRITE OUTPUT RECORD
	J	FEC	
ENDFIL	LDA	=C'EOF'	.INSERT END OF FILE MARKER
	STA	016	
	LDA	#3	
	STA	LENGTH	
	+JSUB	WRREC	.WRITE EOF
	J	@RETADR	.RETURN TO CALLER
	LTORG		
RETADR RESW 1
LENGTH RESW 1